# Generated from ai/comprehensive/v1/comprehensive.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.5.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Enum, Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile, Oneof


_MetadataFields: TypeAlias = Literal["source", "version"]

class Metadata(Message[_MetadataFields]):
    """
    A nested message for testing object properties.

    ```proto
    message ai.comprehensive.v1.Metadata
    ```

    Attributes:
        source:
            ```proto
            string source = 1;
            ```
        version:
            ```proto
            int32 version = 2;
            ```
    """

    __slots__ = ("source", "version")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            source: str = "",
            version: int = 0,
        ) -> None:
            pass

        source: str
        version: int

_ComprehensiveRecordFields: TypeAlias = Literal["text_bounded", "email_address", "website_url", "custom_pattern", "prefixed_code", "score_int", "big_count", "ratio", "latitude", "is_enabled", "status", "tags", "metadata", "notes", "attributes", "text_payload", "binary_payload", "churn_risk", "internal_debug_info", "account_tier"]

class ComprehensiveRecord(Message[_ComprehensiveRecordFields]):
    """
    Comprehensive test message exercising every option and rule combination.

    ```proto
    message ai.comprehensive.v1.ComprehensiveRecord
    ```

    Attributes:
        text_bounded:
            --- String validation variants ---

            ```proto
            string text_bounded = 1;
            ```
        email_address:
            ```proto
            string email_address = 2;
            ```
        website_url:
            ```proto
            string website_url = 3;
            ```
        custom_pattern:
            ```proto
            string custom_pattern = 4;
            ```
        prefixed_code:
            ```proto
            string prefixed_code = 5;
            ```
        score_int:
            --- Numeric validation variants ---

            ```proto
            int32 score_int = 6;
            ```
        big_count:
            ```proto
            int64 big_count = 7;
            ```
        ratio:
            ```proto
            float ratio = 8;
            ```
        latitude:
            ```proto
            double latitude = 9;
            ```
        is_enabled:
            --- Boolean & Enum ---

            ```proto
            bool is_enabled = 10;
            ```
        status:
            ```proto
            ai.comprehensive.v1.Status status = 11;
            ```
        tags:
            --- Repeated / Arrays ---

            ```proto
            repeated string tags = 12;
            ```
        metadata:
            --- Nested message ---

            ```proto
            optional ai.comprehensive.v1.Metadata metadata = 13;
            ```
        notes:
            --- Optional field ---

            ```proto
            optional string notes = 14;
            ```
        attributes:
            --- Map ---

            ```proto
            map<string, string> attributes = 15;
            ```
        payload:
            --- Oneof ---

            ```proto
            oneof payload
            ```
        churn_risk:
            --- Jev custom options testing ---

            ```proto
            bool churn_risk = 18;
            ```
        internal_debug_info:
            ```proto
            string internal_debug_info = 19;
            ```
        account_tier:
            Discrete string choices via Jev options

            ```proto
            string account_tier = 20;
            ```
    """

    __slots__ = ("text_bounded", "email_address", "website_url", "custom_pattern", "prefixed_code", "score_int", "big_count", "ratio", "latitude", "is_enabled", "status", "tags", "metadata", "notes", "attributes", "churn_risk", "internal_debug_info", "account_tier", "payload")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            text_bounded: str = "",
            email_address: str = "",
            website_url: str = "",
            custom_pattern: str = "",
            prefixed_code: str = "",
            score_int: int = 0,
            big_count: int = 0,
            ratio: float = 0,
            latitude: float = 0,
            is_enabled: bool = False,
            status: Status | None = None,
            tags: list[str] | None = None,
            metadata: Metadata | None = None,
            notes: str | None = None,
            attributes: dict[str, str] | None = None,
            payload: Oneof[Literal["text_payload"], str] | Oneof[Literal["binary_payload"], bytes] | None = None,
            churn_risk: bool = False,
            internal_debug_info: str = "",
            account_tier: str = "",
        ) -> None:
            pass

        text_bounded: str
        email_address: str
        website_url: str
        custom_pattern: str
        prefixed_code: str
        score_int: int
        big_count: int
        ratio: float
        latitude: float
        is_enabled: bool
        status: Status
        tags: list[str]
        metadata: Metadata | None
        notes: str
        attributes: dict[str, str]
        payload: Oneof[Literal["text_payload"], str] | Oneof[Literal["binary_payload"], bytes] | None
        churn_risk: bool
        internal_debug_info: str
        account_tier: str

class Status(Enum):
    """
    An enum demonstrating valid options.

    ```proto
    enum ai.comprehensive.v1.Status
    ```

    Attributes:
        UNSPECIFIED:
            ```proto
            STATUS_UNSPECIFIED = 0
            ```
        ACTIVE:
            ```proto
            STATUS_ACTIVE = 1
            ```
        PAUSED:
            ```proto
            STATUS_PAUSED = 2
            ```
        ARCHIVED:
            ```proto
            STATUS_ARCHIVED = 3
            ```
    """

    UNSPECIFIED = 0
    ACTIVE = 1
    PAUSED = 2
    ARCHIVED = 3


_DESC = file_desc(
    b'\n\'ai/comprehensive/v1/comprehensive.proto\x12\x13ai.comprehensive.v1"<\n\x08Metadata\x12\x16\n\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n\x07version\x18\x02 \x01(\x05R\x07version"\xda\x06\n\x13ComprehensiveRecord\x12!\n\x0ctext_bounded\x18\x01 \x01(\tR\x0btextBounded\x12#\n\remail_address\x18\x02 \x01(\tR\x0cemailAddress\x12\x1f\n\x0bwebsite_url\x18\x03 \x01(\tR\nwebsiteUrl\x12%\n\x0ecustom_pattern\x18\x04 \x01(\tR\rcustomPattern\x12#\n\rprefixed_code\x18\x05 \x01(\tR\x0cprefixedCode\x12\x1b\n\tscore_int\x18\x06 \x01(\x05R\x08scoreInt\x12\x1b\n\tbig_count\x18\x07 \x01(\x03R\x08bigCount\x12\x14\n\x05ratio\x18\x08 \x01(\x02R\x05ratio\x12\x1a\n\x08latitude\x18\t \x01(\x01R\x08latitude\x12\x1d\n\nis_enabled\x18\n \x01(\x08R\tisEnabled\x123\n\x06status\x18\x0b \x01(\x0e2\x1b.ai.comprehensive.v1.StatusR\x06status\x12\x12\n\x04tags\x18\x0c \x03(\tR\x04tags\x129\n\x08metadata\x18\r \x01(\x0b2\x1d.ai.comprehensive.v1.MetadataR\x08metadata\x12\x1b\n\x05notes\x18\x0e \x01(\tR\x05notesB\x05\xaa\x01\x02\x08\x01\x12X\n\nattributes\x18\x0f \x03(\x0b28.ai.comprehensive.v1.ComprehensiveRecord.AttributesEntryR\nattributes\x12#\n\x0ctext_payload\x18\x10 \x01(\tH\x00R\x0btextPayload\x12\'\n\x0ebinary_payload\x18\x11 \x01(\x0cH\x00R\rbinaryPayload\x12\x1d\n\nchurn_risk\x18\x12 \x01(\x08R\tchurnRisk\x12.\n\x13internal_debug_info\x18\x13 \x01(\tR\x11internalDebugInfo\x12!\n\x0caccount_tier\x18\x14 \x01(\tR\x0baccountTier\x1a=\n\x0fAttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n\x07payload*[\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x11\n\rSTATUS_PAUSED\x10\x02\x12\x13\n\x0fSTATUS_ARCHIVED\x10\x03B1Z#ai/comprehensive/v1;comprehensivev1\x92\x03\t\x08\x02@\x01\xd2>\x02\x10\x01b\x08editionsp\xe9\x07',
    [],
    {
        "Metadata": Metadata,
        "ComprehensiveRecord": ComprehensiveRecord,
        "Status": Status,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `ai/comprehensive/v1/comprehensive.proto`."""
    return _DESC
