// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/comprehensive/v1/comprehensive.proto (package ai.comprehensive.v1, edition 2024)
// option features.field_presence = IMPLICIT;
// option features.default_symbol_visibility = EXPORT_ALL;
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/comprehensive/v1/comprehensive.proto.
 */
export const file_ai_comprehensive_v1_comprehensive: GenFile = /*@__PURE__*/
  fileDesc("CidhaS9jb21wcmVoZW5zaXZlL3YxL2NvbXByZWhlbnNpdmUucHJvdG8SE2FpLmNvbXByZWhlbnNpdmUudjEiKwoITWV0YWRhdGESDgoGc291cmNlGAEgASgJEg8KB3ZlcnNpb24YAiABKAUi6AQKE0NvbXByZWhlbnNpdmVSZWNvcmQSFAoMdGV4dF9ib3VuZGVkGAEgASgJEhUKDWVtYWlsX2FkZHJlc3MYAiABKAkSEwoLd2Vic2l0ZV91cmwYAyABKAkSFgoOY3VzdG9tX3BhdHRlcm4YBCABKAkSFQoNcHJlZml4ZWRfY29kZRgFIAEoCRIRCglzY29yZV9pbnQYBiABKAUSEQoJYmlnX2NvdW50GAcgASgDEg0KBXJhdGlvGAggASgCEhAKCGxhdGl0dWRlGAkgASgBEhIKCmlzX2VuYWJsZWQYCiABKAgSKwoGc3RhdHVzGAsgASgOMhsuYWkuY29tcHJlaGVuc2l2ZS52MS5TdGF0dXMSDAoEdGFncxgMIAMoCRIvCghtZXRhZGF0YRgNIAEoCzIdLmFpLmNvbXByZWhlbnNpdmUudjEuTWV0YWRhdGESFAoFbm90ZXMYDiABKAlCBaoBAggBEkwKCmF0dHJpYnV0ZXMYDyADKAsyOC5haS5jb21wcmVoZW5zaXZlLnYxLkNvbXByZWhlbnNpdmVSZWNvcmQuQXR0cmlidXRlc0VudHJ5EhYKDHRleHRfcGF5bG9hZBgQIAEoCUgAEhgKDmJpbmFyeV9wYXlsb2FkGBEgASgMSAASEgoKY2h1cm5fcmlzaxgSIAEoCBIbChNpbnRlcm5hbF9kZWJ1Z19pbmZvGBMgASgJEhQKDGFjY291bnRfdGllchgUIAEoCRoxCg9BdHRyaWJ1dGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIJCgdwYXlsb2FkKlsKBlN0YXR1cxIWChJTVEFUVVNfVU5TUEVDSUZJRUQQABIRCg1TVEFUVVNfQUNUSVZFEAESEQoNU1RBVFVTX1BBVVNFRBACEhMKD1NUQVRVU19BUkNISVZFRBADQjFaI2FpL2NvbXByZWhlbnNpdmUvdjE7Y29tcHJlaGVuc2l2ZXYxkgMJCAJAAdI+AhABYghlZGl0aW9uc3DpBw");

/**
 * A nested message for testing object properties.
 *
 * @generated from message ai.comprehensive.v1.Metadata
 */
export type Metadata = Message<"ai.comprehensive.v1.Metadata"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;

  /**
   * @generated from field: int32 version = 2;
   */
  version: number;
};

/**
 * Describes the message ai.comprehensive.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_ai_comprehensive_v1_comprehensive, 0);

/**
 * Comprehensive test message exercising every option and rule combination.
 *
 * @generated from message ai.comprehensive.v1.ComprehensiveRecord
 */
export type ComprehensiveRecord = Message<"ai.comprehensive.v1.ComprehensiveRecord"> & {
  /**
   * --- String validation variants ---
   *
   * @generated from field: string text_bounded = 1;
   */
  textBounded: string;

  /**
   * @generated from field: string email_address = 2;
   */
  emailAddress: string;

  /**
   * @generated from field: string website_url = 3;
   */
  websiteUrl: string;

  /**
   * @generated from field: string custom_pattern = 4;
   */
  customPattern: string;

  /**
   * @generated from field: string prefixed_code = 5;
   */
  prefixedCode: string;

  /**
   * --- Numeric validation variants ---
   *
   * @generated from field: int32 score_int = 6;
   */
  scoreInt: number;

  /**
   * @generated from field: int64 big_count = 7;
   */
  bigCount: bigint;

  /**
   * @generated from field: float ratio = 8;
   */
  ratio: number;

  /**
   * @generated from field: double latitude = 9;
   */
  latitude: number;

  /**
   * --- Boolean & Enum ---
   *
   * @generated from field: bool is_enabled = 10;
   */
  isEnabled: boolean;

  /**
   * @generated from field: ai.comprehensive.v1.Status status = 11;
   */
  status: Status;

  /**
   * --- Repeated / Arrays ---
   *
   * @generated from field: repeated string tags = 12;
   */
  tags: string[];

  /**
   * --- Nested message ---
   *
   * @generated from field: ai.comprehensive.v1.Metadata metadata = 13;
   */
  metadata?: Metadata | undefined;

  /**
   * --- Optional field ---
   *
   * @generated from field: string notes = 14 [features.field_presence = EXPLICIT];
   */
  notes: string;

  /**
   * --- Map ---
   *
   * @generated from field: map<string, string> attributes = 15;
   */
  attributes: { [key: string]: string };

  /**
   * --- Oneof ---
   *
   * @generated from oneof ai.comprehensive.v1.ComprehensiveRecord.payload
   */
  payload: {
    /**
     * @generated from field: string text_payload = 16;
     */
    value: string;
    case: "textPayload";
  } | {
    /**
     * @generated from field: bytes binary_payload = 17;
     */
    value: Uint8Array;
    case: "binaryPayload";
  } | { case: undefined; value?: undefined };

  /**
   * --- Jev custom options testing ---
   *
   * @generated from field: bool churn_risk = 18;
   */
  churnRisk: boolean;

  /**
   * @generated from field: string internal_debug_info = 19;
   */
  internalDebugInfo: string;

  /**
   * Discrete string choices via Jev options
   *
   * @generated from field: string account_tier = 20;
   */
  accountTier: string;
};

/**
 * Describes the message ai.comprehensive.v1.ComprehensiveRecord.
 * Use `create(ComprehensiveRecordSchema)` to create a new message.
 */
export const ComprehensiveRecordSchema: GenMessage<ComprehensiveRecord> = /*@__PURE__*/
  messageDesc(file_ai_comprehensive_v1_comprehensive, 1);

/**
 * An enum demonstrating valid options.
 *
 * @generated from enum ai.comprehensive.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: STATUS_PAUSED = 2;
   */
  PAUSED = 2,

  /**
   * @generated from enum value: STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,
}

/**
 * Describes the enum ai.comprehensive.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_ai_comprehensive_v1_comprehensive, 0);

