// Code generated by protoc-gen-jev. DO NOT EDIT.

package analysisv1

import (
	"context"
	"github.com/sudorandom/protoc-gen-jev/pkg/jev"
)

type EntityJevClient struct {
	client *jev.Client
}

func NewEntityJevClient(client *jev.Client) *EntityJevClient {
	return &EntityJevClient{client: client}
}

func (c *EntityJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "relevance", Type: "score", Instructions: "Relevance score from 0.0 to 1.0.", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Not relevant"}, {Value: 0.5, Description: "Moderately relevant"}, {Value: 1, Description: "Highly relevant"}}}})
}

func (c *EntityJevClient) Evaluate(ctx context.Context, req any) (*Entity, error) {
	decisions, err := c.client.Evaluate(ctx, req, []jev.Question{{Name: "relevance", Type: "score", Instructions: "Relevance score from 0.0 to 1.0.", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Not relevant"}, {Value: 0.5, Description: "Moderately relevant"}, {Value: 1, Description: "Highly relevant"}}}})
	if err != nil {
		return nil, err
	}
	out := &Entity{}
	out.Relevance = float32(decisions.Scores["relevance"].GetValue())
	return out, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *EntityJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*Entity, error) {
	return jev.Batch(ctx, reqs, c.Evaluate)
}

type NotificationJevClient struct {
	client *jev.Client
}

func NewNotificationJevClient(client *jev.Client) *NotificationJevClient {
	return &NotificationJevClient{client: client}
}

func (c *NotificationJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "channel", Type: "choice", Instructions: "Select channel variant", Kind: "oneof", Threshold: 0, Choices: map[string]string{"email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url"}, Levels: []jev.Level{}}})
}

func (c *NotificationJevClient) Evaluate(ctx context.Context, req any) (*Notification, error) {
	decisions, err := c.client.Evaluate(ctx, req, []jev.Question{{Name: "channel", Type: "choice", Instructions: "Select channel variant", Kind: "oneof", Threshold: 0, Choices: map[string]string{"email": "email", "slack_channel": "slack_channel", "webhook_url": "webhook_url"}, Levels: []jev.Level{}}})
	if err != nil {
		return nil, err
	}
	out := &Notification{}
	switch label := decisions.Choices["channel"].GetValue(); label {
	case "email":
		out.Channel = &Notification_Email{Email: label}
	case "slack_channel":
		out.Channel = &Notification_SlackChannel{SlackChannel: label}
	case "webhook_url":
		out.Channel = &Notification_WebhookUrl{WebhookUrl: label}
	}
	return out, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *NotificationJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*Notification, error) {
	return jev.Batch(ctx, reqs, c.Evaluate)
}

type ActionItemJevClient struct {
	client *jev.Client
}

func NewActionItemJevClient(client *jev.Client) *ActionItemJevClient {
	return &ActionItemJevClient{client: client}
}

func (c *ActionItemJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "priority", Type: "choice", Instructions: "Urgency and priority level of the task.", Kind: "enum", Threshold: 0, Choices: map[string]string{"PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": ""}, Levels: []jev.Level{}}, {Name: "requiresImmediateAction", Type: "noul", Instructions: "Whether this task requires immediate escalation or intervention.", Kind: "bool", Threshold: 0.5, Choices: map[string]string{}, Levels: []jev.Level{}}})
}

func (c *ActionItemJevClient) Evaluate(ctx context.Context, req any) (*ActionItem, error) {
	decisions, err := c.client.Evaluate(ctx, req, []jev.Question{{Name: "priority", Type: "choice", Instructions: "Urgency and priority level of the task.", Kind: "enum", Threshold: 0, Choices: map[string]string{"PRIORITY_HIGH": "", "PRIORITY_LOW": "", "PRIORITY_MEDIUM": "", "PRIORITY_URGENT": ""}, Levels: []jev.Level{}}, {Name: "requiresImmediateAction", Type: "noul", Instructions: "Whether this task requires immediate escalation or intervention.", Kind: "bool", Threshold: 0.5, Choices: map[string]string{}, Levels: []jev.Level{}}})
	if err != nil {
		return nil, err
	}
	out := &ActionItem{}
	out.Priority = Priority(Priority_value[decisions.Choices["priority"].GetValue()])
	out.RequiresImmediateAction = decisions.Nouls["requiresImmediateAction"].GetValue()
	return out, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *ActionItemJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*ActionItem, error) {
	return jev.Batch(ctx, reqs, c.Evaluate)
}

type AnalysisReportJevClient struct {
	client *jev.Client
}

func NewAnalysisReportJevClient(client *jev.Client) *AnalysisReportJevClient {
	return &AnalysisReportJevClient{client: client}
}

func (c *AnalysisReportJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "sentiment", Type: "choice", Instructions: "Overall sentiment detected in the text.", Kind: "enum", Threshold: 0, Choices: map[string]string{"SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": ""}, Levels: []jev.Level{}}, {Name: "confidenceScore", Type: "score", Instructions: "Confidence score of the overall analysis between 0.0 and 1.0.", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Low confidence"}, {Value: 0.5, Description: "Medium confidence"}, {Value: 1, Description: "High confidence"}}}})
}

func (c *AnalysisReportJevClient) Evaluate(ctx context.Context, req any) (*AnalysisReport, error) {
	decisions, err := c.client.Evaluate(ctx, req, []jev.Question{{Name: "sentiment", Type: "choice", Instructions: "Overall sentiment detected in the text.", Kind: "enum", Threshold: 0, Choices: map[string]string{"SENTIMENT_NEGATIVE": "", "SENTIMENT_NEUTRAL": "", "SENTIMENT_POSITIVE": ""}, Levels: []jev.Level{}}, {Name: "confidenceScore", Type: "score", Instructions: "Confidence score of the overall analysis between 0.0 and 1.0.", Kind: "float32", Threshold: 0, Choices: map[string]string{}, Levels: []jev.Level{{Value: 0, Description: "Low confidence"}, {Value: 0.5, Description: "Medium confidence"}, {Value: 1, Description: "High confidence"}}}})
	if err != nil {
		return nil, err
	}
	out := &AnalysisReport{}
	out.Sentiment = Sentiment(Sentiment_value[decisions.Choices["sentiment"].GetValue()])
	out.ConfidenceScore = float32(decisions.Scores["confidenceScore"].GetValue())
	return out, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *AnalysisReportJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*AnalysisReport, error) {
	return jev.Batch(ctx, reqs, c.Evaluate)
}
