"""Generated by protoc-gen-jev. DO NOT EDIT."""
from __future__ import annotations
import base64
import json
import math
from typing import Any, cast
from protobuf import Message
from typesafe_sdk import TypeSafeClient, Choice, Noul, Score
from . import analysis_pb as _pb0
from . import analysis_pb as _pb1
from . import analysis_pb as _pb2
from . import analysis_pb as _pb3
def _questions(rules: list[dict[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for q in rules:
        if q["type"] == "choice":
            result[q["name"]] = Choice(instructions=q["instructions"], criteria=q["choices"])
        elif q["type"] == "score":
            result[q["name"]] = Score(instructions=q["instructions"], criteria=[l["description"] for l in q["levels"]])
        else:
            result[q["name"]] = Noul(instructions=q["instructions"])
    return result


def _get(obj: Any, key: str, default: Any = None) -> Any:
    return obj.get(key, default) if isinstance(obj, dict) else getattr(obj, key, default)


def _map_response(response: Any, rules: list[dict[str, Any]], response_field: str | None = None, meta_field: str | None = None) -> dict[str, Any]:
    values: dict[str, Any] = {}
    sentinel = object()
    answers = _get(response, "answers", sentinel)
    canonical = answers is not sentinel
    for q in rules:
        group = answers if canonical else _get(response, {"choice":"choices", "noul":"nouls", "score":"scores"}[q["type"]])
        if not isinstance(group, dict) or q["name"] not in group:
            raise ValueError(f"Missing answer for {q['name']}")
        item = group[q["name"]]
        kind = _get(item, "type", sentinel)
        if (canonical or kind is not sentinel) and kind != q["type"]:
            raise ValueError(f"{q['name']}: expected answer type {q['type']}")
        if q["type"] == "choice":
            label = _get(item, "choice")
            if not isinstance(label, str) or label not in q["choices"]:
                raise ValueError(f"{q['name']}: invalid choice")
            if q.get("oneof"):
                values[label] = base64.b64encode(label.encode("ascii")).decode("ascii") if q["oneof"][label] == "bytes" else label
            elif q.get("typed"):
                choice_obj: dict[str, Any] = {"value": label}
                conf = _get(item, "confidence")
                if isinstance(conf, (int, float)):
                    choice_obj["confidence"] = float(conf)
                probs = _get(item, "probabilities")
                if isinstance(probs, dict):
                    choice_obj["probabilities"] = probs
                values[q["field"]] = choice_obj
            else:
                values[q["field"]] = label
        elif q["type"] == "noul":
            value = _get(item, "noul", sentinel)
            if value is sentinel:
                value = _get(item, "result")
            if isinstance(value, bool):
                flag = value
                prob = 1.0 if value else 0.0
            elif isinstance(value, (int, float)) and math.isfinite(value) and 0 <= value <= 1:
                flag = value >= q["threshold"]
                prob = float(value)
            else:
                raise ValueError(f"{q['name']}: invalid noul")
            if q.get("typed"):
                noul_obj: dict[str, Any] = {"value": flag, "probability": prob}
                conf = _get(item, "confidence")
                if isinstance(conf, (int, float)):
                    noul_obj["confidence"] = float(conf)
                values[q["field"]] = noul_obj
            else:
                values[q["field"]] = flag
        else:
            pos = _get(item, "score")
            levels = q["levels"]
            if isinstance(pos, bool) or not isinstance(pos, (int, float)) or not math.isfinite(pos) or not 0 <= pos <= len(levels)-1:
                raise ValueError(f"{q['name']}: invalid score")
            i = int(pos)
            value = float(levels[i]["value"])
            if i + 1 < len(levels):
                value = (1 - (pos - i)) * value + (pos - i) * levels[i + 1]["value"]
            if not math.isfinite(value):
                raise ValueError(f"{q['name']}: non-finite domain value")
            if q["kind"].startswith(("int", "uint")):
                whole = math.floor(abs(value))
                value = math.copysign(whole + (1 if abs(value) - whole >= 0.5 else 0), value)
            if q.get("typed"):
                score_obj: dict[str, Any] = {"value": value, "score": float(pos)}
                conf = _get(item, "confidence")
                if isinstance(conf, (int, float)):
                    score_obj["confidence"] = float(conf)
                probs = _get(item, "probabilities")
                if isinstance(probs, dict):
                    score_obj["probabilities"] = probs
                legend = _get(item, "legend")
                if isinstance(legend, dict):
                    score_obj["legend"] = legend
                values[q["field"]] = score_obj
            else:
                values[q["field"]] = str(int(value)) if q["kind"] in ("int64", "uint64") else value
    if response_field:
        resp_dict = dict(response) if isinstance(response, dict) else vars(response).copy()
        if "answers" not in resp_dict:
            answers_fallback = {}
            for key in ("choices", "nouls", "scores"):
                grp = _get(resp_dict, key)
                if isinstance(grp, dict):
                    answers_fallback.update(grp)
            if answers_fallback:
                resp_dict["answers"] = answers_fallback
        ans_map = resp_dict.get("answers")
        if isinstance(ans_map, dict):
            ans_map = dict(ans_map)
            for k, item in ans_map.items():
                if isinstance(item, dict):
                    item = dict(item)
                    if isinstance(item.get("noul"), bool):
                        item["noul"] = 1.0 if item["noul"] else 0.0
                    if isinstance(item.get("result"), bool):
                        item["noul"] = 1.0 if item["result"] else 0.0
                    ans_map[k] = item
            resp_dict["answers"] = ans_map
        values[response_field] = resp_dict
    if meta_field:
        meta_obj: dict[str, Any] = {}
        model_name = _get(response, "model")
        if isinstance(model_name, str):
            meta_obj["model"] = model_name
        usage = _get(response, "usage")
        if usage is not None:
            usage_obj: dict[str, Any] = {}
            in_tok = _get(usage, "input_tokens")
            out_tok = _get(usage, "output_tokens")
            if isinstance(in_tok, int):
                usage_obj["input_tokens"] = in_tok
            if isinstance(out_tok, int):
                usage_obj["output_tokens"] = out_tok
            meta_obj["usage"] = usage_obj
        values[meta_field] = meta_obj
    return values


class EntityJevClient:
    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):
        self._client = client
        self._api_key = api_key
    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()
        return self._client
    def build_questions(self) -> dict[str, Any]:
        return _questions(json.loads("[{\"name\":\"relevance\",\"type\":\"score\",\"instructions\":\"Relevance score from 0.0 to 1.0.\",\"field\":\"relevance\",\"kind\":\"float32\",\"levels\":[{\"value\":0,\"description\":\"Not relevant\"},{\"value\":0.5,\"description\":\"Moderately relevant\"},{\"value\":1,\"description\":\"Highly relevant\"}],\"threshold\":0}]"))
    def evaluate(self, req: Message | dict[str, Any] | list[Any] | str) -> _pb0.Entity:
        rules = json.loads("[{\"name\":\"relevance\",\"type\":\"score\",\"instructions\":\"Relevance score from 0.0 to 1.0.\",\"field\":\"relevance\",\"kind\":\"float32\",\"levels\":[{\"value\":0,\"description\":\"Not relevant\"},{\"value\":0.5,\"description\":\"Moderately relevant\"},{\"value\":1,\"description\":\"Highly relevant\"}],\"threshold\":0}]")
        response = self.client.system_one(state=json.loads(req.to_json()) if isinstance(req, Message) else req, questions=_questions(rules))
        return _pb0.Entity.from_json(json.dumps(_map_response(response, rules)), ignore_unknown_fields=True)
    def batch_evaluate(self, reqs: list[Message | dict[str, Any] | list[Any] | str]) -> list[_pb0.Entity]:
        return [self.evaluate(req) for req in reqs]

class NotificationJevClient:
    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):
        self._client = client
        self._api_key = api_key
    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()
        return self._client
    def build_questions(self) -> dict[str, Any]:
        return _questions(json.loads("[{\"name\":\"channel\",\"type\":\"choice\",\"instructions\":\"Select channel variant\",\"field\":\"channel\",\"kind\":\"oneof\",\"choices\":{\"email\":\"email\",\"slack_channel\":\"slack_channel\",\"webhook_url\":\"webhook_url\"},\"threshold\":0,\"oneof\":{\"email\":\"string\",\"slack_channel\":\"string\",\"webhook_url\":\"string\"}}]"))
    def evaluate(self, req: Message | dict[str, Any] | list[Any] | str) -> _pb1.Notification:
        rules = json.loads("[{\"name\":\"channel\",\"type\":\"choice\",\"instructions\":\"Select channel variant\",\"field\":\"channel\",\"kind\":\"oneof\",\"choices\":{\"email\":\"email\",\"slack_channel\":\"slack_channel\",\"webhook_url\":\"webhook_url\"},\"threshold\":0,\"oneof\":{\"email\":\"string\",\"slack_channel\":\"string\",\"webhook_url\":\"string\"}}]")
        response = self.client.system_one(state=json.loads(req.to_json()) if isinstance(req, Message) else req, questions=_questions(rules))
        return _pb1.Notification.from_json(json.dumps(_map_response(response, rules)), ignore_unknown_fields=True)
    def batch_evaluate(self, reqs: list[Message | dict[str, Any] | list[Any] | str]) -> list[_pb1.Notification]:
        return [self.evaluate(req) for req in reqs]

class ActionItemJevClient:
    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):
        self._client = client
        self._api_key = api_key
    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()
        return self._client
    def build_questions(self) -> dict[str, Any]:
        return _questions(json.loads("[{\"name\":\"priority\",\"type\":\"choice\",\"instructions\":\"Urgency and priority level of the task.\",\"field\":\"priority\",\"kind\":\"enum\",\"choices\":{\"PRIORITY_HIGH\":\"\",\"PRIORITY_LOW\":\"\",\"PRIORITY_MEDIUM\":\"\",\"PRIORITY_URGENT\":\"\"},\"threshold\":0},{\"name\":\"requiresImmediateAction\",\"type\":\"noul\",\"instructions\":\"Whether this task requires immediate escalation or intervention.\",\"field\":\"requires_immediate_action\",\"kind\":\"bool\",\"threshold\":0.5}]"))
    def evaluate(self, req: Message | dict[str, Any] | list[Any] | str) -> _pb2.ActionItem:
        rules = json.loads("[{\"name\":\"priority\",\"type\":\"choice\",\"instructions\":\"Urgency and priority level of the task.\",\"field\":\"priority\",\"kind\":\"enum\",\"choices\":{\"PRIORITY_HIGH\":\"\",\"PRIORITY_LOW\":\"\",\"PRIORITY_MEDIUM\":\"\",\"PRIORITY_URGENT\":\"\"},\"threshold\":0},{\"name\":\"requiresImmediateAction\",\"type\":\"noul\",\"instructions\":\"Whether this task requires immediate escalation or intervention.\",\"field\":\"requires_immediate_action\",\"kind\":\"bool\",\"threshold\":0.5}]")
        response = self.client.system_one(state=json.loads(req.to_json()) if isinstance(req, Message) else req, questions=_questions(rules))
        return _pb2.ActionItem.from_json(json.dumps(_map_response(response, rules)), ignore_unknown_fields=True)
    def batch_evaluate(self, reqs: list[Message | dict[str, Any] | list[Any] | str]) -> list[_pb2.ActionItem]:
        return [self.evaluate(req) for req in reqs]

class AnalysisReportJevClient:
    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):
        self._client = client
        self._api_key = api_key
    @property
    def client(self) -> TypeSafeClient:
        if self._client is None:
            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()
        return self._client
    def build_questions(self) -> dict[str, Any]:
        return _questions(json.loads("[{\"name\":\"sentiment\",\"type\":\"choice\",\"instructions\":\"Overall sentiment detected in the text.\",\"field\":\"sentiment\",\"kind\":\"enum\",\"choices\":{\"SENTIMENT_NEGATIVE\":\"\",\"SENTIMENT_NEUTRAL\":\"\",\"SENTIMENT_POSITIVE\":\"\"},\"threshold\":0},{\"name\":\"confidenceScore\",\"type\":\"score\",\"instructions\":\"Confidence score of the overall analysis between 0.0 and 1.0.\",\"field\":\"confidence_score\",\"kind\":\"float32\",\"levels\":[{\"value\":0,\"description\":\"Low confidence\"},{\"value\":0.5,\"description\":\"Medium confidence\"},{\"value\":1,\"description\":\"High confidence\"}],\"threshold\":0}]"))
    def evaluate(self, req: Message | dict[str, Any] | list[Any] | str) -> _pb3.AnalysisReport:
        rules = json.loads("[{\"name\":\"sentiment\",\"type\":\"choice\",\"instructions\":\"Overall sentiment detected in the text.\",\"field\":\"sentiment\",\"kind\":\"enum\",\"choices\":{\"SENTIMENT_NEGATIVE\":\"\",\"SENTIMENT_NEUTRAL\":\"\",\"SENTIMENT_POSITIVE\":\"\"},\"threshold\":0},{\"name\":\"confidenceScore\",\"type\":\"score\",\"instructions\":\"Confidence score of the overall analysis between 0.0 and 1.0.\",\"field\":\"confidence_score\",\"kind\":\"float32\",\"levels\":[{\"value\":0,\"description\":\"Low confidence\"},{\"value\":0.5,\"description\":\"Medium confidence\"},{\"value\":1,\"description\":\"High confidence\"}],\"threshold\":0}]")
        response = self.client.system_one(state=json.loads(req.to_json()) if isinstance(req, Message) else req, questions=_questions(rules))
        return _pb3.AnalysisReport.from_json(json.dumps(_map_response(response, rules)), ignore_unknown_fields=True)
    def batch_evaluate(self, reqs: list[Message | dict[str, Any] | list[Any] | str]) -> list[_pb3.AnalysisReport]:
        return [self.evaluate(req) for req in reqs]

