package codegen

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/gofeaturespb"

	"github.com/bufbuild/protoc-gen-jev/internal/model"
)

func GenerateGo(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, services []model.ServiceSpec) error {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_jev.pb.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-jev. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"github.com/bufbuild/protoc-gen-jev/pkg/jev"`)
	g.P(")")
	g.P()
	constructor := func(name string) {
		g.P("type ", name, " struct {")
		g.P("	client *jev.Client")
		g.P("}")
		g.P()
		g.P("func New", name, "(client *jev.Client) *", name, " {")
		g.P("	return &", name, "{client: client}")
		g.P("}")
		g.P()
	}
	emit := func(client, method, build, input string, spec model.MessageSpec) {
		output := g.QualifiedGoIdent(spec.Ref.GoIdent)
		g.P("func (c *", client, ") ", build, "() map[string]any {")
		g.P("	return jev.Questions(", goRules(spec), ")")
		g.P("}")
		g.P()
		g.P("func (c *", client, ") ", method, "(ctx context.Context, req ", input, ") (*", output, ", error) {")
		g.P("	decisions, err := c.client.Evaluate(ctx, req, ", goRules(spec), ")")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	out := &", output, "{}")
		goAssignments(g, spec)
		g.P("	return out, nil")
		g.P("}")
		g.P()
		g.P("// Batch", method, " evaluates requests sequentially and stops at the first error.")
		g.P("func (c *", client, ") Batch", method, "(ctx context.Context, reqs []", input, ") ([]*", output, ", error) {")
		g.P("	return jev.Batch(ctx, reqs, c.", method, ")")
		g.P("}")
		g.P()
	}
	for _, spec := range specs {
		name := spec.MessageName + "JevClient"
		constructor(name)
		emit(name, "Evaluate", "BuildQuestions", "any", spec)
	}
	for _, svc := range services {
		name := "Jev" + svc.ServiceName
		constructor(name)
		for _, m := range svc.Methods {
			emit(name, m.Name, "Build"+m.Name+"Questions", "*"+g.QualifiedGoIdent(m.Input.GoIdent), m.QuestionSpec)
		}
	}
	return nil
}

func goRules(spec model.MessageSpec) string {
	var items []string
	for _, q := range runtimeRules(spec) {
		var choices, levels []string
		for _, key := range sortedKeys(q.Choices) {
			choices = append(choices, fmt.Sprintf("%q:%q", key, q.Choices[key]))
		}
		for _, l := range q.Levels {
			levels = append(levels, fmt.Sprintf("{Value:%s,Description:%q}", strconv.FormatFloat(l.Value, 'g', -1, 64), l.Description))
		}
		items = append(items, fmt.Sprintf("{Name:%q,Type:%q,Instructions:%q,Kind:%q,Threshold:%v,Choices:map[string]string{%s},Levels:[]jev.Level{%s}}", q.Name, q.Type, q.Instructions, q.Kind, q.Threshold, strings.Join(choices, ","), strings.Join(levels, ",")))
	}
	return "[]jev.Question{" + strings.Join(items, ",") + "}"
}

// goAssignments uses the schema's Go identifiers and types, so the runtime only
// needs to validate decisions, never reflect over application messages.
func goAssignments(g *protogen.GeneratedFile, spec model.MessageSpec) {
	opaque := spec.Ref.APILevel == gofeaturespb.GoFeatures_API_OPAQUE
	assign := func(field, value string) {
		if opaque {
			g.P("out.Set", field, "(", value, ")")
		} else {
			g.P("out.", field, " = ", value)
		}
	}
	for _, name := range spec.Order {
		q := spec.Questions[name]
		source := "decisions." + map[model.QuestionType]string{model.TypeChoice: "Choices", model.TypeNoul: "Nouls", model.TypeScore: "Scores"}[q.Type] + "[" + strconv.Quote(name) + "]"
		if q.IsOneof {
			g.P("switch label := ", source, ".GetValue(); label {")
			for _, field := range spec.Ref.Fields {
				if field.Oneof == nil || field.Oneof.GoName != q.GoField {
					continue
				}
				label := string(field.Desc.Name())
				value := "label"
				if q.OneofCaseKinds[label] == "bytes" {
					value = "[]byte(label)"
				}
				if opaque {
					g.P("case ", strconv.Quote(label), ":")
					assign(field.GoName, value)
				} else {
					g.P("case ", strconv.Quote(label), ": out.", field.Oneof.GoName, " = &", g.QualifiedGoIdent(field.GoIdent), "{", field.GoName, ":", value, "}")
				}
			}
			g.P("}")
			continue
		}
		for _, field := range spec.Ref.Fields {
			if field.GoName != q.GoField {
				continue
			}
			value := source
			if !q.IsTypedAnswer {
				value += ".GetValue()"
				if q.IsEnum {
					value = g.QualifiedGoIdent(field.Enum.GoIdent) + "(" + g.QualifiedGoIdent(protogen.GoIdent{GoName: field.Enum.GoIdent.GoName + "_value", GoImportPath: field.Enum.GoIdent.GoImportPath}) + "[" + value + "])"
				} else if q.Type == model.TypeScore {
					value = q.FieldType + "(" + value + ")"
				}
				if field.Desc.HasPresence() && !opaque {
					g.P("value", field.GoName, " := ", value)
					value = "&value" + field.GoName
				}
			}
			assign(field.GoName, value)
		}
	}
	for _, field := range spec.Ref.Fields {
		if field.Desc.JSONName() == spec.MetaField {
			assign(field.GoName, "decisions.Meta")
		}
		if field.Desc.JSONName() == spec.ResponseField {
			assign(field.GoName, "decisions.Response")
		}
	}
}
