package codegen

import (
	_ "embed"
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/bufbuild/protoc-gen-jev/internal/model"
	"google.golang.org/protobuf/compiler/protogen"
)

//go:embed templates/runtime.py
var pyRuntime string

func GeneratePython(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, services []model.ServiceSpec) error {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_jev.py", "")
	g.P(`"""Generated by protoc-gen-jev. DO NOT EDIT."""`)
	g.P("from __future__ import annotations")
	g.P("import base64\nimport json\nimport math\nfrom typing import Any, cast")
	g.P("from protobuf import Message")
	g.P("from typesafe_sdk import TypeSafeClient, Choice, Noul, Score")
	aliases := map[*protogen.Message]string{}
	for i, m := range messages(specs, services) {
		alias := fmt.Sprintf("_pb%d", i)
		module, name, err := pythonImport(file.Desc.Path(), m.Desc.ParentFile().Path())
		if err != nil {
			return err
		}
		g.P("from ", module, " import ", name, " as ", alias)
		aliases[m] = alias + "." + strings.Join(messagePath(m), ".")
	}
	g.P(pyRuntime)
	constructor := func(name string) {
		g.P("class ", name, ":")
		g.P("    def __init__(self, client: TypeSafeClient | None = None, api_key: str | None = None):")
		g.P("        self._client = client\n        self._api_key = api_key")
		g.P("    @property\n    def client(self) -> TypeSafeClient:\n        if self._client is None:\n            self._client = TypeSafeClient(api_key=self._api_key) if self._api_key is not None else TypeSafeClient()\n        return self._client")
	}
	emit := func(method, build, input, state string, spec model.MessageSpec) error {
		output := aliases[spec.Ref]
		rj, err := rulesJSON(spec)
		if err != nil {
			return err
		}
		rules := "json.loads(" + strconv.Quote(rj) + ")"
		respArgs := ""
		if spec.ResponseField != "" || spec.MetaField != "" {
			respArgs = ", " + strconv.Quote(spec.ResponseField) + ", " + strconv.Quote(spec.MetaField)
		}
		g.P("    def ", build, "(self) -> dict[str, Any]:\n        return _questions(", rules, ")")
		g.P("    def ", method, "(self, req: ", input, ") -> ", output, ":")
		g.P("        rules = ", rules)
		g.P("        response = self.client.system_one(state=", state, ", questions=_questions(rules))")
		g.P("        return ", output, ".from_json(json.dumps(_map_response(response, rules", respArgs, ")), ignore_unknown_fields=True)")
		g.P("    def batch_", method, "(self, reqs: list[", input, "]) -> list[", output, "]:\n        return [self.", method, "(req) for req in reqs]")
		return nil
	}
	for _, spec := range specs {
		constructor(spec.MessageName + "JevClient")
		if err := emit("evaluate", "build_questions", "Message | dict[str, Any] | list[Any] | str", "json.loads(req.to_json()) if isinstance(req, Message) else req", spec); err != nil {
			return err
		}
		g.P()
	}
	for _, svc := range services {
		constructor("Jev" + svc.ServiceName)
		for _, m := range svc.Methods {
			method := ToSnakeCase(m.Name)
			if err := emit(method, "build_"+method+"_questions", aliases[m.Input], "json.loads(req.to_json())", m.QuestionSpec); err != nil {
				return err
			}
		}
		g.P()
	}
	return nil
}

// pythonImport keeps bindings relative to the generated package, wherever it is installed.
func pythonImport(source, target string) (string, string, error) {
	rel, err := filepath.Rel(filepath.Dir(source), filepath.Dir(target))
	if err != nil {
		return "", "", fmt.Errorf("failed to calculate relative python import path between %s and %s: %w", source, target, err)
	}
	prefix := "."
	var parts []string
	for _, part := range strings.Split(filepath.ToSlash(rel), "/") {
		switch part {
		case "..":
			prefix += "."
		case ".":
		default:
			parts = append(parts, part)
		}
	}
	return prefix + strings.Join(parts, "."), strings.TrimSuffix(filepath.Base(target), ".proto") + "_pb", nil
}

func ToSnakeCase(s string) string {
	var out strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := runes[i-1]
			var next rune
			if i+1 < len(runes) {
				next = runes[i+1]
			}
			if (prev >= 'a' && prev <= 'z') || (prev >= '0' && prev <= '9') ||
				(next >= 'a' && next <= 'z' && prev >= 'A' && prev <= 'Z') {
				out.WriteByte('_')
			}
		}
		out.WriteRune(r)
	}
	return strings.ToLower(out.String())
}
