package codegen

import (
	_ "embed"
	"fmt"
	"strconv"
	"strings"

	"github.com/sudorandom/protoc-gen-jev/internal/model"
	"google.golang.org/protobuf/compiler/protogen"
)

//go:embed templates/runtime.ts
var tsRuntime string

func GenerateTypeScript(gen *protogen.Plugin, file *protogen.File, specs []model.MessageSpec, services []model.ServiceSpec) error {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_jev.ts", "")
	g.P("// Code generated by protoc-gen-jev. DO NOT EDIT.")
	g.P(`import { TypeSafeClient, choice, score, noul, type EntryType } from "@typesafe-ai/sdk";`)
	g.P(`import { fromJson, toJson, type JsonObject, type JsonValue, type MessageShape } from "@bufbuild/protobuf";`)
	aliases := map[*protogen.Message]string{}
	for i, m := range messages(specs, services) {
		alias := fmt.Sprintf("JevSchema%d", i)
		aliases[m] = alias
		relMod, err := relativeModule(gen, file, m)
		if err != nil {
			return err
		}
		g.P(fmt.Sprintf("import { %sSchema as %s } from %q;", strings.Join(messagePath(m), "_"), alias, relMod))
	}
	g.P(tsRuntime)
	emit := func(method, build, input, state string, spec model.MessageSpec) error {
		output := "MessageShape<typeof " + aliases[spec.Ref] + ">"
		respArgs := ""
		if spec.ResponseField != "" || spec.MetaField != "" {
			respArgs = ", " + strconv.Quote(spec.ResponseField) + ", " + strconv.Quote(spec.MetaField)
		}
		rj, err := rulesJSON(spec)
		if err != nil {
			return err
		}
		g.P("  ", build, "() { return questions(", rj, "); }")
		g.P("  async ", method, "(req: ", input, "): Promise<", output, "> {")
		g.P("    const rules: Rule[] = ", rj, ";")
		g.P("    const response = object(await this.client.systemOne({state: ", state, ", questions: questions(rules)}), \"response\");")
		g.P("    return fromJson(", aliases[spec.Ref], ", mapResponse(response, rules", respArgs, "), { ignoreUnknownFields: true });")
		g.P("  }")
		batch := "batch" + strings.ToUpper(method[:1]) + method[1:]
		g.P("  // Sequential execution; stops at the first error without starting later requests.")
		g.P("  async ", batch, "(reqs: ", input, "[]): Promise<", output, "[]> {")
		g.P("    const results: ", output, "[] = []; for (const req of reqs) results.push(await this.", method, "(req)); return results;")
		g.P("  }")
		return nil
	}
	constructor := func(name string) {
		g.P("export class ", name, " {\n  constructor(private readonly client: TypeSafeClient = new TypeSafeClient()) {}")
	}
	for _, spec := range specs {
		constructor(spec.MessageName + "JevClient")
		if err := emit("evaluate", "buildQuestions", "EntryType", "req", spec); err != nil {
			return err
		}
		g.P("}")
	}
	for _, svc := range services {
		constructor("Jev" + svc.ServiceName)
		for _, m := range svc.Methods {
			if err := emit(strings.ToLower(m.Name[:1])+m.Name[1:], "build"+m.Name+"Questions", "MessageShape<typeof "+aliases[m.Input]+">", "toJson("+aliases[m.Input]+", req) as EntryType", m.QuestionSpec); err != nil {
				return err
			}
		}
		g.P("}")
	}
	return nil
}
