// Code generated by protoc-gen-jev. DO NOT EDIT.

package sharedv1

import (
	"context"
	"github.com/sudorandom/protoc-gen-jev/pkg/jev"
)

type ExternalResponseJevClient struct {
	client *jev.Client
}

func NewExternalResponseJevClient(client *jev.Client) *ExternalResponseJevClient {
	return &ExternalResponseJevClient{client: client}
}

func (c *ExternalResponseJevClient) BuildQuestions() map[string]any {
	return jev.Questions([]jev.Question{{Name: "accepted", Type: "noul", Instructions: "Evaluate accepted", Kind: "bool", Threshold: 0.5, Choices: map[string]string{}, Levels: []jev.Level{}}})
}

func (c *ExternalResponseJevClient) Evaluate(ctx context.Context, req any) (*ExternalResponse, error) {
	decisions, err := c.client.Evaluate(ctx, req, []jev.Question{{Name: "accepted", Type: "noul", Instructions: "Evaluate accepted", Kind: "bool", Threshold: 0.5, Choices: map[string]string{}, Levels: []jev.Level{}}})
	if err != nil {
		return nil, err
	}
	out := &ExternalResponse{}
	out.Accepted = decisions.Nouls["accepted"].GetValue()
	return out, nil
}

// BatchEvaluate evaluates requests sequentially and stops at the first error.
func (c *ExternalResponseJevClient) BatchEvaluate(ctx context.Context, reqs []any) ([]*ExternalResponse, error) {
	return jev.Batch(ctx, reqs, c.Evaluate)
}
