// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/contract/v1/contract.proto (package ai.contract.v1, edition 2024)
// option features.field_presence = IMPLICIT;
// option features.default_symbol_visibility = EXPORT_ALL;
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Status } from "../../shared/v1/shared_pb";
import { file_ai_shared_v1_shared } from "../../shared/v1/shared_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/contract/v1/contract.proto.
 */
export const file_ai_contract_v1_contract: GenFile = /*@__PURE__*/
  fileDesc("Ch1haS9jb250cmFjdC92MS9jb250cmFjdC5wcm90bxIOYWkuY29udHJhY3QudjEiOgoPRXZhbHVhdGVSZXF1ZXN0EhIKCmlucHV0X3RleHQYASABKAkSEwoLaW5wdXRfY291bnQYAiABKAQizgIKEEV2YWx1YXRlUmVzcG9uc2USEwoEZmxhZxgBIAEoCEIFqgECCAESFQoGcmF0aW5nGAIgASgFQgWqAQIIARINCgVjb3VudBgDIAEoDRIRCgliaWdfY291bnQYBCABKAMSFAoMYmlnX3Vuc2lnbmVkGAUgASgEEhMKC2ZpeGVkX2NvdW50GAYgASgHEhoKEnNpZ25lZF9maXhlZF9jb3VudBgHIAEoEBIXCgRyaXNrGAggASgIUglyaXNrLWZsYWcSJAoGc3RhdHVzGAkgASgOMhQuYWkuc2hhcmVkLnYxLlN0YXR1cxIUCgVsYWJlbBgKIAEoCUIFqgECCAESEAoIYm91bmRhcnkYDiABKAMSDwoFZW1haWwYCyABKAlIABIQCgZiaW5hcnkYDCABKAxIABISCghleGNsdWRlZBgNIAEoCUgAQgcKBXJvdXRlIlsKCUNvbnRhaW5lchojCg1OZXN0ZWRSZXF1ZXN0EhIKCmlucHV0X3RleHQYASABKAkaKQoOTmVzdGVkUmVzcG9uc2USFwoIYWNjZXB0ZWQYASABKAhCBaoBAggBQlJaRGdpdGh1Yi5jb20vYnVmYnVpbGQvcHJvdG9jLWdlbi1qZXYvZ2VuL2pldi9haS9jb250cmFjdC92MTtjb250cmFjdHYxkgMJCAJAAdI+AhABYghlZGl0aW9uc3DpBw", [file_ai_shared_v1_shared]);

/**
 * @generated from message ai.contract.v1.EvaluateRequest
 */
export type EvaluateRequest = Message<"ai.contract.v1.EvaluateRequest"> & {
  /**
   * @generated from field: string input_text = 1;
   */
  inputText: string;

  /**
   * @generated from field: uint64 input_count = 2;
   */
  inputCount: bigint;
};

/**
 * Describes the message ai.contract.v1.EvaluateRequest.
 * Use `create(EvaluateRequestSchema)` to create a new message.
 */
export const EvaluateRequestSchema: GenMessage<EvaluateRequest> = /*@__PURE__*/
  messageDesc(file_ai_contract_v1_contract, 0);

/**
 * @generated from message ai.contract.v1.EvaluateResponse
 */
export type EvaluateResponse = Message<"ai.contract.v1.EvaluateResponse"> & {
  /**
   * @generated from field: bool flag = 1 [features.field_presence = EXPLICIT];
   */
  flag: boolean;

  /**
   * @generated from field: int32 rating = 2 [features.field_presence = EXPLICIT];
   */
  rating: number;

  /**
   * @generated from field: uint32 count = 3;
   */
  count: number;

  /**
   * @generated from field: int64 big_count = 4;
   */
  bigCount: bigint;

  /**
   * @generated from field: uint64 big_unsigned = 5;
   */
  bigUnsigned: bigint;

  /**
   * @generated from field: fixed32 fixed_count = 6;
   */
  fixedCount: number;

  /**
   * @generated from field: sfixed64 signed_fixed_count = 7;
   */
  signedFixedCount: bigint;

  /**
   * @generated from field: bool risk = 8 [json_name = "risk-flag"];
   */
  risk: boolean;

  /**
   * @generated from field: ai.shared.v1.Status status = 9;
   */
  status: Status;

  /**
   * @generated from field: string label = 10 [features.field_presence = EXPLICIT];
   */
  label: string;

  /**
   * @generated from field: int64 boundary = 14;
   */
  boundary: bigint;

  /**
   * @generated from oneof ai.contract.v1.EvaluateResponse.route
   */
  route: {
    /**
     * @generated from field: string email = 11;
     */
    value: string;
    case: "email";
  } | {
    /**
     * @generated from field: bytes binary = 12;
     */
    value: Uint8Array;
    case: "binary";
  } | {
    /**
     * @generated from field: string excluded = 13;
     */
    value: string;
    case: "excluded";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ai.contract.v1.EvaluateResponse.
 * Use `create(EvaluateResponseSchema)` to create a new message.
 */
export const EvaluateResponseSchema: GenMessage<EvaluateResponse> = /*@__PURE__*/
  messageDesc(file_ai_contract_v1_contract, 1);

/**
 * @generated from message ai.contract.v1.Container
 */
export type Container = Message<"ai.contract.v1.Container"> & {
};

/**
 * Describes the message ai.contract.v1.Container.
 * Use `create(ContainerSchema)` to create a new message.
 */
export const ContainerSchema: GenMessage<Container> = /*@__PURE__*/
  messageDesc(file_ai_contract_v1_contract, 2);

/**
 * @generated from message ai.contract.v1.Container.NestedRequest
 */
export type Container_NestedRequest = Message<"ai.contract.v1.Container.NestedRequest"> & {
  /**
   * @generated from field: string input_text = 1;
   */
  inputText: string;
};

/**
 * Describes the message ai.contract.v1.Container.NestedRequest.
 * Use `create(Container_NestedRequestSchema)` to create a new message.
 */
export const Container_NestedRequestSchema: GenMessage<Container_NestedRequest> = /*@__PURE__*/
  messageDesc(file_ai_contract_v1_contract, 2, 0);

/**
 * @generated from message ai.contract.v1.Container.NestedResponse
 */
export type Container_NestedResponse = Message<"ai.contract.v1.Container.NestedResponse"> & {
  /**
   * @generated from field: bool accepted = 1 [features.field_presence = EXPLICIT];
   */
  accepted: boolean;
};

/**
 * Describes the message ai.contract.v1.Container.NestedResponse.
 * Use `create(Container_NestedResponseSchema)` to create a new message.
 */
export const Container_NestedResponseSchema: GenMessage<Container_NestedResponse> = /*@__PURE__*/
  messageDesc(file_ai_contract_v1_contract, 2, 1);

