// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: jev/v1/response.proto

package jevv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Meta reports execution metadata from the Jev provider.
type Meta struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model string                 `protobuf:"bytes,1,opt,name=model"`
	xxx_hidden_Usage *Usage                 `protobuf:"bytes,2,opt,name=usage"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_jev_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Meta) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *Meta) GetUsage() *Usage {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *Meta) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *Meta) SetUsage(v *Usage) {
	x.xxx_hidden_Usage = v
}

func (x *Meta) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *Meta) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

type Meta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model string
	Usage *Usage
}

func (b0 Meta_builder) Build() *Meta {
	m0 := &Meta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Usage = b.Usage
	return m0
}

// Usage reports token metrics from the provider.
type Usage struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InputTokens  int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens"`
	xxx_hidden_OutputTokens int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_jev_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.xxx_hidden_InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.xxx_hidden_OutputTokens
	}
	return 0
}

func (x *Usage) SetInputTokens(v int32) {
	x.xxx_hidden_InputTokens = v
}

func (x *Usage) SetOutputTokens(v int32) {
	x.xxx_hidden_OutputTokens = v
}

type Usage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InputTokens  int32
	OutputTokens int32
}

func (b0 Usage_builder) Build() *Usage {
	m0 := &Usage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InputTokens = b.InputTokens
	x.xxx_hidden_OutputTokens = b.OutputTokens
	return m0
}

// Noul encapsulates a binary decision along with its calibrated probability and confidence.
type Noul struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       bool                   `protobuf:"varint,1,opt,name=value"`
	xxx_hidden_Probability float64                `protobuf:"fixed64,2,opt,name=probability"`
	xxx_hidden_Confidence  float64                `protobuf:"fixed64,3,opt,name=confidence"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Noul) Reset() {
	*x = Noul{}
	mi := &file_jev_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noul) ProtoMessage() {}

func (x *Noul) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Noul) GetValue() bool {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return false
}

func (x *Noul) GetProbability() float64 {
	if x != nil {
		return x.xxx_hidden_Probability
	}
	return 0
}

func (x *Noul) GetConfidence() float64 {
	if x != nil {
		return x.xxx_hidden_Confidence
	}
	return 0
}

func (x *Noul) SetValue(v bool) {
	x.xxx_hidden_Value = v
}

func (x *Noul) SetProbability(v float64) {
	x.xxx_hidden_Probability = v
}

func (x *Noul) SetConfidence(v float64) {
	x.xxx_hidden_Confidence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Noul) HasConfidence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Noul) ClearConfidence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Confidence = 0
}

type Noul_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value       bool
	Probability float64
	Confidence  *float64
}

func (b0 Noul_builder) Build() *Noul {
	m0 := &Noul{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Probability = b.Probability
	if b.Confidence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Confidence = *b.Confidence
	}
	return m0
}

// Score encapsulates a numerical or rubric evaluation along with position and distributions.
type Score struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value         float64                `protobuf:"fixed64,1,opt,name=value"`
	xxx_hidden_Score         float64                `protobuf:"fixed64,2,opt,name=score"`
	xxx_hidden_Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence"`
	xxx_hidden_Probabilities map[string]float64     `protobuf:"bytes,4,rep,name=probabilities" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	xxx_hidden_Legend        map[string]string      `protobuf:"bytes,5,rep,name=legend" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_jev_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Score) GetValue() float64 {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return 0
}

func (x *Score) GetScore() float64 {
	if x != nil {
		return x.xxx_hidden_Score
	}
	return 0
}

func (x *Score) GetConfidence() float64 {
	if x != nil {
		return x.xxx_hidden_Confidence
	}
	return 0
}

func (x *Score) GetProbabilities() map[string]float64 {
	if x != nil {
		return x.xxx_hidden_Probabilities
	}
	return nil
}

func (x *Score) GetLegend() map[string]string {
	if x != nil {
		return x.xxx_hidden_Legend
	}
	return nil
}

func (x *Score) SetValue(v float64) {
	x.xxx_hidden_Value = v
}

func (x *Score) SetScore(v float64) {
	x.xxx_hidden_Score = v
}

func (x *Score) SetConfidence(v float64) {
	x.xxx_hidden_Confidence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Score) SetProbabilities(v map[string]float64) {
	x.xxx_hidden_Probabilities = v
}

func (x *Score) SetLegend(v map[string]string) {
	x.xxx_hidden_Legend = v
}

func (x *Score) HasConfidence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Score) ClearConfidence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Confidence = 0
}

type Score_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value         float64
	Score         float64
	Confidence    *float64
	Probabilities map[string]float64
	Legend        map[string]string
}

func (b0 Score_builder) Build() *Score {
	m0 := &Score{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Score = b.Score
	if b.Confidence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Confidence = *b.Confidence
	}
	x.xxx_hidden_Probabilities = b.Probabilities
	x.xxx_hidden_Legend = b.Legend
	return m0
}

// Choice encapsulates a categorical decision along with confidence and distributions.
type Choice struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value         string                 `protobuf:"bytes,1,opt,name=value"`
	xxx_hidden_Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence"`
	xxx_hidden_Probabilities map[string]float64     `protobuf:"bytes,3,rep,name=probabilities" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_jev_v1_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Choice) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Choice) GetConfidence() float64 {
	if x != nil {
		return x.xxx_hidden_Confidence
	}
	return 0
}

func (x *Choice) GetProbabilities() map[string]float64 {
	if x != nil {
		return x.xxx_hidden_Probabilities
	}
	return nil
}

func (x *Choice) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *Choice) SetConfidence(v float64) {
	x.xxx_hidden_Confidence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Choice) SetProbabilities(v map[string]float64) {
	x.xxx_hidden_Probabilities = v
}

func (x *Choice) HasConfidence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Choice) ClearConfidence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Confidence = 0
}

type Choice_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value         string
	Confidence    *float64
	Probabilities map[string]float64
}

func (b0 Choice_builder) Build() *Choice {
	m0 := &Choice{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	if b.Confidence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Confidence = *b.Confidence
	}
	x.xxx_hidden_Probabilities = b.Probabilities
	return m0
}

// WireResponse models the raw JSON envelope returned by Jev over HTTP.
type WireResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model   string                 `protobuf:"bytes,1,opt,name=model"`
	xxx_hidden_Usage   *Usage                 `protobuf:"bytes,2,opt,name=usage"`
	xxx_hidden_Answers map[string]*Answer     `protobuf:"bytes,3,rep,name=answers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Choices map[string]*Answer     `protobuf:"bytes,4,rep,name=choices" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Scores  map[string]*Answer     `protobuf:"bytes,5,rep,name=scores" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Nouls   map[string]*Answer     `protobuf:"bytes,6,rep,name=nouls" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WireResponse) Reset() {
	*x = WireResponse{}
	mi := &file_jev_v1_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireResponse) ProtoMessage() {}

func (x *WireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WireResponse) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *WireResponse) GetUsage() *Usage {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *WireResponse) GetAnswers() map[string]*Answer {
	if x != nil {
		return x.xxx_hidden_Answers
	}
	return nil
}

func (x *WireResponse) GetChoices() map[string]*Answer {
	if x != nil {
		return x.xxx_hidden_Choices
	}
	return nil
}

func (x *WireResponse) GetScores() map[string]*Answer {
	if x != nil {
		return x.xxx_hidden_Scores
	}
	return nil
}

func (x *WireResponse) GetNouls() map[string]*Answer {
	if x != nil {
		return x.xxx_hidden_Nouls
	}
	return nil
}

func (x *WireResponse) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *WireResponse) SetUsage(v *Usage) {
	x.xxx_hidden_Usage = v
}

func (x *WireResponse) SetAnswers(v map[string]*Answer) {
	x.xxx_hidden_Answers = v
}

func (x *WireResponse) SetChoices(v map[string]*Answer) {
	x.xxx_hidden_Choices = v
}

func (x *WireResponse) SetScores(v map[string]*Answer) {
	x.xxx_hidden_Scores = v
}

func (x *WireResponse) SetNouls(v map[string]*Answer) {
	x.xxx_hidden_Nouls = v
}

func (x *WireResponse) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *WireResponse) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

type WireResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model   string
	Usage   *Usage
	Answers map[string]*Answer
	Choices map[string]*Answer
	Scores  map[string]*Answer
	Nouls   map[string]*Answer
}

func (b0 WireResponse_builder) Build() *WireResponse {
	m0 := &WireResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Usage = b.Usage
	x.xxx_hidden_Answers = b.Answers
	x.xxx_hidden_Choices = b.Choices
	x.xxx_hidden_Scores = b.Scores
	x.xxx_hidden_Nouls = b.Nouls
	return m0
}

// Answer encapsulates the provider's evaluation for a single question.
type Answer struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type          string                 `protobuf:"bytes,1,opt,name=type"`
	xxx_hidden_Choice        string                 `protobuf:"bytes,2,opt,name=choice"`
	xxx_hidden_Noul          float64                `protobuf:"fixed64,3,opt,name=noul"`
	xxx_hidden_Score         float64                `protobuf:"fixed64,4,opt,name=score"`
	xxx_hidden_Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence"`
	xxx_hidden_Probabilities map[string]float64     `protobuf:"bytes,6,rep,name=probabilities" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	xxx_hidden_Legend        map[string]string      `protobuf:"bytes,7,rep,name=legend" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_jev_v1_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Answer) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *Answer) GetChoice() string {
	if x != nil {
		return x.xxx_hidden_Choice
	}
	return ""
}

func (x *Answer) GetNoul() float64 {
	if x != nil {
		return x.xxx_hidden_Noul
	}
	return 0
}

func (x *Answer) GetScore() float64 {
	if x != nil {
		return x.xxx_hidden_Score
	}
	return 0
}

func (x *Answer) GetConfidence() float64 {
	if x != nil {
		return x.xxx_hidden_Confidence
	}
	return 0
}

func (x *Answer) GetProbabilities() map[string]float64 {
	if x != nil {
		return x.xxx_hidden_Probabilities
	}
	return nil
}

func (x *Answer) GetLegend() map[string]string {
	if x != nil {
		return x.xxx_hidden_Legend
	}
	return nil
}

func (x *Answer) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *Answer) SetChoice(v string) {
	x.xxx_hidden_Choice = v
}

func (x *Answer) SetNoul(v float64) {
	x.xxx_hidden_Noul = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Answer) SetScore(v float64) {
	x.xxx_hidden_Score = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Answer) SetConfidence(v float64) {
	x.xxx_hidden_Confidence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *Answer) SetProbabilities(v map[string]float64) {
	x.xxx_hidden_Probabilities = v
}

func (x *Answer) SetLegend(v map[string]string) {
	x.xxx_hidden_Legend = v
}

func (x *Answer) HasNoul() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Answer) HasScore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Answer) HasConfidence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Answer) ClearNoul() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Noul = 0
}

func (x *Answer) ClearScore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Score = 0
}

func (x *Answer) ClearConfidence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Confidence = 0
}

type Answer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type          string
	Choice        string
	Noul          *float64
	Score         *float64
	Confidence    *float64
	Probabilities map[string]float64
	Legend        map[string]string
}

func (b0 Answer_builder) Build() *Answer {
	m0 := &Answer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Choice = b.Choice
	if b.Noul != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Noul = *b.Noul
	}
	if b.Score != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Score = *b.Score
	}
	if b.Confidence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Confidence = *b.Confidence
	}
	x.xxx_hidden_Probabilities = b.Probabilities
	x.xxx_hidden_Legend = b.Legend
	return m0
}

// Response contains the provider evaluation metadata and answers.
// Placing a field of this type on a decision response message causes protoc-gen-jev
// to automatically populate it with the full model execution details.
type Response struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model   string                 `protobuf:"bytes,1,opt,name=model"`
	xxx_hidden_Usage   *Usage                 `protobuf:"bytes,2,opt,name=usage"`
	xxx_hidden_Answers map[string]*Answer     `protobuf:"bytes,3,rep,name=answers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_jev_v1_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_jev_v1_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Response) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *Response) GetUsage() *Usage {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *Response) GetAnswers() map[string]*Answer {
	if x != nil {
		return x.xxx_hidden_Answers
	}
	return nil
}

func (x *Response) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *Response) SetUsage(v *Usage) {
	x.xxx_hidden_Usage = v
}

func (x *Response) SetAnswers(v map[string]*Answer) {
	x.xxx_hidden_Answers = v
}

func (x *Response) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *Response) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

type Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model   string
	Usage   *Usage
	Answers map[string]*Answer
}

func (b0 Response_builder) Build() *Response {
	m0 := &Response{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Usage = b.Usage
	x.xxx_hidden_Answers = b.Answers
	return m0
}

var File_jev_v1_response_proto protoreflect.FileDescriptor

const file_jev_v1_response_proto_rawDesc = "" +
	"\n" +
	"\x15jev/v1/response.proto\x12\x06jev.v1\"A\n" +
	"\x04Meta\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\x05usage\x18\x02 \x01(\v2\r.jev.v1.UsageR\x05usage\"O\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\"e\n" +
	"\x04Noul\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\x12%\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01B\x05\xaa\x01\x02\b\x01R\n" +
	"confidence\"\xd2\x02\n" +
	"\x05Score\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12%\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01B\x05\xaa\x01\x02\b\x01R\n" +
	"confidence\x12F\n" +
	"\rprobabilities\x18\x04 \x03(\v2 .jev.v1.Score.ProbabilitiesEntryR\rprobabilities\x121\n" +
	"\x06legend\x18\x05 \x03(\v2\x19.jev.v1.Score.LegendEntryR\x06legend\x1a@\n" +
	"\x12ProbabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLegendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x06Choice\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12%\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01B\x05\xaa\x01\x02\b\x01R\n" +
	"confidence\x12G\n" +
	"\rprobabilities\x18\x03 \x03(\v2!.jev.v1.Choice.ProbabilitiesEntryR\rprobabilities\x1a@\n" +
	"\x12ProbabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe1\x04\n" +
	"\fWireResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\x05usage\x18\x02 \x01(\v2\r.jev.v1.UsageR\x05usage\x12;\n" +
	"\aanswers\x18\x03 \x03(\v2!.jev.v1.WireResponse.AnswersEntryR\aanswers\x12;\n" +
	"\achoices\x18\x04 \x03(\v2!.jev.v1.WireResponse.ChoicesEntryR\achoices\x128\n" +
	"\x06scores\x18\x05 \x03(\v2 .jev.v1.WireResponse.ScoresEntryR\x06scores\x125\n" +
	"\x05nouls\x18\x06 \x03(\v2\x1f.jev.v1.WireResponse.NoulsEntryR\x05nouls\x1aJ\n" +
	"\fAnswersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.jev.v1.AnswerR\x05value:\x028\x01\x1aJ\n" +
	"\fChoicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.jev.v1.AnswerR\x05value:\x028\x01\x1aI\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.jev.v1.AnswerR\x05value:\x028\x01\x1aH\n" +
	"\n" +
	"NoulsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.jev.v1.AnswerR\x05value:\x028\x01\"\x8d\x03\n" +
	"\x06Answer\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06choice\x18\x02 \x01(\tR\x06choice\x12\x19\n" +
	"\x04noul\x18\x03 \x01(\x01B\x05\xaa\x01\x02\b\x01R\x04noul\x12\x1b\n" +
	"\x05score\x18\x04 \x01(\x01B\x05\xaa\x01\x02\b\x01R\x05score\x12%\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01B\x05\xaa\x01\x02\b\x01R\n" +
	"confidence\x12G\n" +
	"\rprobabilities\x18\x06 \x03(\v2!.jev.v1.Answer.ProbabilitiesEntryR\rprobabilities\x122\n" +
	"\x06legend\x18\a \x03(\v2\x1a.jev.v1.Answer.LegendEntryR\x06legend\x1a@\n" +
	"\x12ProbabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLegendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\bResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\x05usage\x18\x02 \x01(\v2\r.jev.v1.UsageR\x05usage\x127\n" +
	"\aanswers\x18\x03 \x03(\v2\x1d.jev.v1.Response.AnswersEntryR\aanswers\x1aJ\n" +
	"\fAnswersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.jev.v1.AnswerR\x05value:\x028\x01B<Z5github.com/sudorandom/protoc-gen-jev/pkg/jev/v1;jevv1\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_jev_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_jev_v1_response_proto_goTypes = []any{
	(*Meta)(nil),         // 0: jev.v1.Meta
	(*Usage)(nil),        // 1: jev.v1.Usage
	(*Noul)(nil),         // 2: jev.v1.Noul
	(*Score)(nil),        // 3: jev.v1.Score
	(*Choice)(nil),       // 4: jev.v1.Choice
	(*WireResponse)(nil), // 5: jev.v1.WireResponse
	(*Answer)(nil),       // 6: jev.v1.Answer
	(*Response)(nil),     // 7: jev.v1.Response
	nil,                  // 8: jev.v1.Score.ProbabilitiesEntry
	nil,                  // 9: jev.v1.Score.LegendEntry
	nil,                  // 10: jev.v1.Choice.ProbabilitiesEntry
	nil,                  // 11: jev.v1.WireResponse.AnswersEntry
	nil,                  // 12: jev.v1.WireResponse.ChoicesEntry
	nil,                  // 13: jev.v1.WireResponse.ScoresEntry
	nil,                  // 14: jev.v1.WireResponse.NoulsEntry
	nil,                  // 15: jev.v1.Answer.ProbabilitiesEntry
	nil,                  // 16: jev.v1.Answer.LegendEntry
	nil,                  // 17: jev.v1.Response.AnswersEntry
}
var file_jev_v1_response_proto_depIdxs = []int32{
	1,  // 0: jev.v1.Meta.usage:type_name -> jev.v1.Usage
	8,  // 1: jev.v1.Score.probabilities:type_name -> jev.v1.Score.ProbabilitiesEntry
	9,  // 2: jev.v1.Score.legend:type_name -> jev.v1.Score.LegendEntry
	10, // 3: jev.v1.Choice.probabilities:type_name -> jev.v1.Choice.ProbabilitiesEntry
	1,  // 4: jev.v1.WireResponse.usage:type_name -> jev.v1.Usage
	11, // 5: jev.v1.WireResponse.answers:type_name -> jev.v1.WireResponse.AnswersEntry
	12, // 6: jev.v1.WireResponse.choices:type_name -> jev.v1.WireResponse.ChoicesEntry
	13, // 7: jev.v1.WireResponse.scores:type_name -> jev.v1.WireResponse.ScoresEntry
	14, // 8: jev.v1.WireResponse.nouls:type_name -> jev.v1.WireResponse.NoulsEntry
	15, // 9: jev.v1.Answer.probabilities:type_name -> jev.v1.Answer.ProbabilitiesEntry
	16, // 10: jev.v1.Answer.legend:type_name -> jev.v1.Answer.LegendEntry
	1,  // 11: jev.v1.Response.usage:type_name -> jev.v1.Usage
	17, // 12: jev.v1.Response.answers:type_name -> jev.v1.Response.AnswersEntry
	6,  // 13: jev.v1.WireResponse.AnswersEntry.value:type_name -> jev.v1.Answer
	6,  // 14: jev.v1.WireResponse.ChoicesEntry.value:type_name -> jev.v1.Answer
	6,  // 15: jev.v1.WireResponse.ScoresEntry.value:type_name -> jev.v1.Answer
	6,  // 16: jev.v1.WireResponse.NoulsEntry.value:type_name -> jev.v1.Answer
	6,  // 17: jev.v1.Response.AnswersEntry.value:type_name -> jev.v1.Answer
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_jev_v1_response_proto_init() }
func file_jev_v1_response_proto_init() {
	if File_jev_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jev_v1_response_proto_rawDesc), len(file_jev_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jev_v1_response_proto_goTypes,
		DependencyIndexes: file_jev_v1_response_proto_depIdxs,
		MessageInfos:      file_jev_v1_response_proto_msgTypes,
	}.Build()
	File_jev_v1_response_proto = out.File
	file_jev_v1_response_proto_goTypes = nil
	file_jev_v1_response_proto_depIdxs = nil
}
