// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ai/rules/v1/rules.proto (package ai.rules.v1, edition 2024)
// option features.field_presence = IMPLICIT;
// option features.default_symbol_visibility = EXPORT_ALL;
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/rules/v1/rules.proto.
 */
export const file_ai_rules_v1_rules: GenFile = /*@__PURE__*/
  fileDesc("ChdhaS9ydWxlcy92MS9ydWxlcy5wcm90bxILYWkucnVsZXMudjEi3gMKDlJ1bGVUZXN0UmVjb3JkEg8KBWVtYWlsGAEgASgJSAASDQoDc21zGAIgASgJSAASGwoRcHVzaF9ub3RpZmljYXRpb24YAyABKAlIABIcCg1vcHRpb25hbF9ub3RlGAQgASgJQgWqAQIIARIpCg5leGVjdXRpb25fbW9kZRgFIAEoDjIRLmFpLnJ1bGVzLnYxLk1vZGUSKAoNZmlsdGVyZWRfbW9kZRgGIAEoDjIRLmFpLnJ1bGVzLnYxLk1vZGUSFAoMcmF0aW5nX3NtYWxsGAcgASgFEhUKDXJhdGluZ19zdHJpY3QYCCABKAUSFQoNZGlzY3JldGVfY29kZRgJIAEoBRITCgtsYXJnZV9zY2FsZRgKIAEoAxITCgt0ZW1wZXJhdHVyZRgLIAEoAhIWCg5kaXNjcmV0ZV9yYXRpbxgMIAEoAhIaChJzZWN1cml0eV9jbGVhcmFuY2UYDSABKAkSFQoNZGVjaXNpb25fZmxhZxgOIAEoCRIcChRjdXN0b21fYm91bmRlZF9zY29yZRgPIAEoAhIUCgxzZWNyZXRfdG9rZW4YECABKAkSHAoUZnJlZWZvcm1fZGVzY3JpcHRpb24YESABKAlCEQoPZGVsaXZlcnlfbWV0aG9kKmEKBE1vZGUSFAoQTU9ERV9VTlNQRUNJRklFRBAAEg0KCU1PREVfRkFTVBABEhEKDU1PREVfQkFMQU5DRUQQAhIRCg1NT0RFX0FDQ1VSQVRFEAMSDgoKTU9ERV9ERUJVRxAEQiFaE2FpL3J1bGVzL3YxO3J1bGVzdjGSAwkIAkAB0j4CEAFiCGVkaXRpb25zcOkH");

/**
 * @generated from message ai.rules.v1.RuleTestRecord
 */
export type RuleTestRecord = Message<"ai.rules.v1.RuleTestRecord"> & {
  /**
   * 1. Oneof mutual exclusion -> maps to Choice
   *
   * @generated from oneof ai.rules.v1.RuleTestRecord.delivery_method
   */
  deliveryMethod: {
    /**
     * @generated from field: string email = 1;
     */
    value: string;
    case: "email";
  } | {
    /**
     * @generated from field: string sms = 2;
     */
    value: string;
    case: "sms";
  } | {
    /**
     * @generated from field: string push_notification = 3;
     */
    value: string;
    case: "pushNotification";
  } | { case: undefined; value?: undefined };

  /**
   * 2. Explicit field presence -> must NOT be treated as a oneof Choice!
   *
   * @generated from field: string optional_note = 4 [features.field_presence = EXPLICIT];
   */
  optionalNote: string;

  /**
   * 3. Enum restricted by choices -> Choice with only [MODE_FAST, MODE_BALANCED]
   *
   * @generated from field: ai.rules.v1.Mode execution_mode = 5;
   */
  executionMode: Mode;

  /**
   * 4. Enum restricted by not_in -> Choice omitting MODE_DEBUG
   *
   * @generated from field: ai.rules.v1.Mode filtered_mode = 6;
   */
  filteredMode: Mode;

  /**
   * 5. Integer with small range (<= 10) -> exact sequence [1..5]
   *
   * @generated from field: int32 rating_small = 7;
   */
  ratingSmall: number;

  /**
   * 6. Integer with explicit scale -> [1, 2, 3]
   *
   * @generated from field: int32 rating_strict = 8;
   */
  ratingStrict: number;

  /**
   * 7. Integer with discrete allowed values -> ["10", "20", "50", "100"]
   *
   * @generated from field: int32 discrete_code = 9;
   */
  discreteCode: number;

  /**
   * 8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]
   *
   * @generated from field: int64 large_scale = 10;
   */
  largeScale: bigint;

  /**
   * 9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]
   *
   * @generated from field: float temperature = 11;
   */
  temperature: number;

  /**
   * 10. Float discrete values -> ["0.2", "0.5", "0.8"]
   *
   * @generated from field: float discrete_ratio = 12;
   */
  discreteRatio: number;

  /**
   * 11. String with allowed set of values -> Choice
   *
   * @generated from field: string security_clearance = 13;
   */
  securityClearance: string;

  /**
   * 12. String with custom Jev criteria options -> Choice
   *
   * @generated from field: string decision_flag = 14;
   */
  decisionFlag: string;

  /**
   * 13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]
   *
   * @generated from field: float custom_bounded_score = 15;
   */
  customBoundedScore: number;

  /**
   * 14. Explicitly skipped field -> MUST NOT appear in questions
   *
   * @generated from field: string secret_token = 16;
   */
  secretToken: string;

  /**
   * 15. Freeform text without rules -> omitted from Jev questions
   *
   * @generated from field: string freeform_description = 17;
   */
  freeformDescription: string;
};

/**
 * Describes the message ai.rules.v1.RuleTestRecord.
 * Use `create(RuleTestRecordSchema)` to create a new message.
 */
export const RuleTestRecordSchema: GenMessage<RuleTestRecord> = /*@__PURE__*/
  messageDesc(file_ai_rules_v1_rules, 0);

/**
 * @generated from enum ai.rules.v1.Mode
 */
export enum Mode {
  /**
   * @generated from enum value: MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MODE_FAST = 1;
   */
  FAST = 1,

  /**
   * @generated from enum value: MODE_BALANCED = 2;
   */
  BALANCED = 2,

  /**
   * @generated from enum value: MODE_ACCURATE = 3;
   */
  ACCURATE = 3,

  /**
   * @generated from enum value: MODE_DEBUG = 4;
   */
  DEBUG = 4,
}

/**
 * Describes the enum ai.rules.v1.Mode.
 */
export const ModeSchema: GenEnum<Mode> = /*@__PURE__*/
  enumDesc(file_ai_rules_v1_rules, 0);

