// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ai/rules/v1/rules.proto

package rulesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_FAST        Mode = 1
	Mode_MODE_BALANCED    Mode = 2
	Mode_MODE_ACCURATE    Mode = 3
	Mode_MODE_DEBUG       Mode = 4
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_FAST",
		2: "MODE_BALANCED",
		3: "MODE_ACCURATE",
		4: "MODE_DEBUG",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_FAST":        1,
		"MODE_BALANCED":    2,
		"MODE_ACCURATE":    3,
		"MODE_DEBUG":       4,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_rules_v1_rules_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_ai_rules_v1_rules_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_ai_rules_v1_rules_proto_rawDescGZIP(), []int{0}
}

type RuleTestRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. Oneof mutual exclusion -> maps to Choice
	//
	// Types that are valid to be assigned to DeliveryMethod:
	//
	//	*RuleTestRecord_Email
	//	*RuleTestRecord_Sms
	//	*RuleTestRecord_PushNotification
	DeliveryMethod isRuleTestRecord_DeliveryMethod `protobuf_oneof:"delivery_method"`
	// 2. Explicit field presence -> must NOT be treated as a oneof Choice!
	OptionalNote *string `protobuf:"bytes,4,opt,name=optional_note,json=optionalNote" json:"optional_note,omitempty"`
	// 3. Enum restricted by choices -> Choice with only [MODE_FAST, MODE_BALANCED]
	ExecutionMode Mode `protobuf:"varint,5,opt,name=execution_mode,json=executionMode,enum=ai.rules.v1.Mode" json:"execution_mode,omitempty"`
	// 4. Enum restricted by not_in -> Choice omitting MODE_DEBUG
	FilteredMode Mode `protobuf:"varint,6,opt,name=filtered_mode,json=filteredMode,enum=ai.rules.v1.Mode" json:"filtered_mode,omitempty"`
	// 5. Integer with small range (<= 10) -> exact sequence [1..5]
	RatingSmall int32 `protobuf:"varint,7,opt,name=rating_small,json=ratingSmall" json:"rating_small,omitempty"`
	// 6. Integer with explicit scale -> [1, 2, 3]
	RatingStrict int32 `protobuf:"varint,8,opt,name=rating_strict,json=ratingStrict" json:"rating_strict,omitempty"`
	// 7. Integer with discrete allowed values -> ["10", "20", "50", "100"]
	DiscreteCode int32 `protobuf:"varint,9,opt,name=discrete_code,json=discreteCode" json:"discrete_code,omitempty"`
	// 8. Large integer range -> 5-tier interpolated rubric [0, 250, 500, 750, 1000]
	LargeScale int64 `protobuf:"varint,10,opt,name=large_scale,json=largeScale" json:"large_scale,omitempty"`
	// 9. Float continuous range -> 5-tier interpolated rubric [-40.0, -15.0, 10.0, 35.0, 60.0]
	Temperature float32 `protobuf:"fixed32,11,opt,name=temperature" json:"temperature,omitempty"`
	// 10. Float discrete values -> ["0.2", "0.5", "0.8"]
	DiscreteRatio float32 `protobuf:"fixed32,12,opt,name=discrete_ratio,json=discreteRatio" json:"discrete_ratio,omitempty"`
	// 11. String with allowed set of values -> Choice
	SecurityClearance string `protobuf:"bytes,13,opt,name=security_clearance,json=securityClearance" json:"security_clearance,omitempty"`
	// 12. String with custom Jev criteria options -> Choice
	DecisionFlag string `protobuf:"bytes,14,opt,name=decision_flag,json=decisionFlag" json:"decision_flag,omitempty"`
	// 13. Float with custom Jev min/max options -> [10.0, 20.0, 30.0, 40.0, 50.0]
	CustomBoundedScore float32 `protobuf:"fixed32,15,opt,name=custom_bounded_score,json=customBoundedScore" json:"custom_bounded_score,omitempty"`
	// 14. Explicitly skipped field -> MUST NOT appear in questions
	SecretToken string `protobuf:"bytes,16,opt,name=secret_token,json=secretToken" json:"secret_token,omitempty"`
	// 15. Freeform text without rules -> omitted from Jev questions
	FreeformDescription string `protobuf:"bytes,17,opt,name=freeform_description,json=freeformDescription" json:"freeform_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuleTestRecord) Reset() {
	*x = RuleTestRecord{}
	mi := &file_ai_rules_v1_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleTestRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleTestRecord) ProtoMessage() {}

func (x *RuleTestRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ai_rules_v1_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleTestRecord.ProtoReflect.Descriptor instead.
func (*RuleTestRecord) Descriptor() ([]byte, []int) {
	return file_ai_rules_v1_rules_proto_rawDescGZIP(), []int{0}
}

func (x *RuleTestRecord) GetDeliveryMethod() isRuleTestRecord_DeliveryMethod {
	if x != nil {
		return x.DeliveryMethod
	}
	return nil
}

func (x *RuleTestRecord) GetEmail() string {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*RuleTestRecord_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *RuleTestRecord) GetSms() string {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*RuleTestRecord_Sms); ok {
			return x.Sms
		}
	}
	return ""
}

func (x *RuleTestRecord) GetPushNotification() string {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*RuleTestRecord_PushNotification); ok {
			return x.PushNotification
		}
	}
	return ""
}

func (x *RuleTestRecord) GetOptionalNote() string {
	if x != nil && x.OptionalNote != nil {
		return *x.OptionalNote
	}
	return ""
}

func (x *RuleTestRecord) GetExecutionMode() Mode {
	if x != nil {
		return x.ExecutionMode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *RuleTestRecord) GetFilteredMode() Mode {
	if x != nil {
		return x.FilteredMode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *RuleTestRecord) GetRatingSmall() int32 {
	if x != nil {
		return x.RatingSmall
	}
	return 0
}

func (x *RuleTestRecord) GetRatingStrict() int32 {
	if x != nil {
		return x.RatingStrict
	}
	return 0
}

func (x *RuleTestRecord) GetDiscreteCode() int32 {
	if x != nil {
		return x.DiscreteCode
	}
	return 0
}

func (x *RuleTestRecord) GetLargeScale() int64 {
	if x != nil {
		return x.LargeScale
	}
	return 0
}

func (x *RuleTestRecord) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *RuleTestRecord) GetDiscreteRatio() float32 {
	if x != nil {
		return x.DiscreteRatio
	}
	return 0
}

func (x *RuleTestRecord) GetSecurityClearance() string {
	if x != nil {
		return x.SecurityClearance
	}
	return ""
}

func (x *RuleTestRecord) GetDecisionFlag() string {
	if x != nil {
		return x.DecisionFlag
	}
	return ""
}

func (x *RuleTestRecord) GetCustomBoundedScore() float32 {
	if x != nil {
		return x.CustomBoundedScore
	}
	return 0
}

func (x *RuleTestRecord) GetSecretToken() string {
	if x != nil {
		return x.SecretToken
	}
	return ""
}

func (x *RuleTestRecord) GetFreeformDescription() string {
	if x != nil {
		return x.FreeformDescription
	}
	return ""
}

type isRuleTestRecord_DeliveryMethod interface {
	isRuleTestRecord_DeliveryMethod()
}

type RuleTestRecord_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,oneof"`
}

type RuleTestRecord_Sms struct {
	Sms string `protobuf:"bytes,2,opt,name=sms,oneof"`
}

type RuleTestRecord_PushNotification struct {
	PushNotification string `protobuf:"bytes,3,opt,name=push_notification,json=pushNotification,oneof"`
}

func (*RuleTestRecord_Email) isRuleTestRecord_DeliveryMethod() {}

func (*RuleTestRecord_Sms) isRuleTestRecord_DeliveryMethod() {}

func (*RuleTestRecord_PushNotification) isRuleTestRecord_DeliveryMethod() {}

var File_ai_rules_v1_rules_proto protoreflect.FileDescriptor

const file_ai_rules_v1_rules_proto_rawDesc = "" +
	"\n" +
	"\x17ai/rules/v1/rules.proto\x12\vai.rules.v1\"\xcf\x05\n" +
	"\x0eRuleTestRecord\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x12\n" +
	"\x03sms\x18\x02 \x01(\tH\x00R\x03sms\x12-\n" +
	"\x11push_notification\x18\x03 \x01(\tH\x00R\x10pushNotification\x12*\n" +
	"\roptional_note\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x01R\foptionalNote\x128\n" +
	"\x0eexecution_mode\x18\x05 \x01(\x0e2\x11.ai.rules.v1.ModeR\rexecutionMode\x126\n" +
	"\rfiltered_mode\x18\x06 \x01(\x0e2\x11.ai.rules.v1.ModeR\ffilteredMode\x12!\n" +
	"\frating_small\x18\a \x01(\x05R\vratingSmall\x12#\n" +
	"\rrating_strict\x18\b \x01(\x05R\fratingStrict\x12#\n" +
	"\rdiscrete_code\x18\t \x01(\x05R\fdiscreteCode\x12\x1f\n" +
	"\vlarge_scale\x18\n" +
	" \x01(\x03R\n" +
	"largeScale\x12 \n" +
	"\vtemperature\x18\v \x01(\x02R\vtemperature\x12%\n" +
	"\x0ediscrete_ratio\x18\f \x01(\x02R\rdiscreteRatio\x12-\n" +
	"\x12security_clearance\x18\r \x01(\tR\x11securityClearance\x12#\n" +
	"\rdecision_flag\x18\x0e \x01(\tR\fdecisionFlag\x120\n" +
	"\x14custom_bounded_score\x18\x0f \x01(\x02R\x12customBoundedScore\x12!\n" +
	"\fsecret_token\x18\x10 \x01(\tR\vsecretToken\x121\n" +
	"\x14freeform_description\x18\x11 \x01(\tR\x13freeformDescriptionB\x11\n" +
	"\x0fdelivery_method*a\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMODE_FAST\x10\x01\x12\x11\n" +
	"\rMODE_BALANCED\x10\x02\x12\x11\n" +
	"\rMODE_ACCURATE\x10\x03\x12\x0e\n" +
	"\n" +
	"MODE_DEBUG\x10\x04B\x1fZ\x13ai/rules/v1;rulesv1\x92\x03\a\xd2>\x02\x10\x01\b\x02b\beditionsp\xe9\a"

var (
	file_ai_rules_v1_rules_proto_rawDescOnce sync.Once
	file_ai_rules_v1_rules_proto_rawDescData []byte
)

func file_ai_rules_v1_rules_proto_rawDescGZIP() []byte {
	file_ai_rules_v1_rules_proto_rawDescOnce.Do(func() {
		file_ai_rules_v1_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_rules_v1_rules_proto_rawDesc), len(file_ai_rules_v1_rules_proto_rawDesc)))
	})
	return file_ai_rules_v1_rules_proto_rawDescData
}

var file_ai_rules_v1_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_rules_v1_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_rules_v1_rules_proto_goTypes = []any{
	(Mode)(0),              // 0: ai.rules.v1.Mode
	(*RuleTestRecord)(nil), // 1: ai.rules.v1.RuleTestRecord
}
var file_ai_rules_v1_rules_proto_depIdxs = []int32{
	0, // 0: ai.rules.v1.RuleTestRecord.execution_mode:type_name -> ai.rules.v1.Mode
	0, // 1: ai.rules.v1.RuleTestRecord.filtered_mode:type_name -> ai.rules.v1.Mode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_rules_v1_rules_proto_init() }
func file_ai_rules_v1_rules_proto_init() {
	if File_ai_rules_v1_rules_proto != nil {
		return
	}
	file_ai_rules_v1_rules_proto_msgTypes[0].OneofWrappers = []any{
		(*RuleTestRecord_Email)(nil),
		(*RuleTestRecord_Sms)(nil),
		(*RuleTestRecord_PushNotification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_rules_v1_rules_proto_rawDesc), len(file_ai_rules_v1_rules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_rules_v1_rules_proto_goTypes,
		DependencyIndexes: file_ai_rules_v1_rules_proto_depIdxs,
		EnumInfos:         file_ai_rules_v1_rules_proto_enumTypes,
		MessageInfos:      file_ai_rules_v1_rules_proto_msgTypes,
	}.Build()
	File_ai_rules_v1_rules_proto = out.File
	file_ai_rules_v1_rules_proto_goTypes = nil
	file_ai_rules_v1_rules_proto_depIdxs = nil
}
